markdown: kramdown
theme: jekyll-theme-primer
sass:
  sass_dir: assets/css
collections:
  policies:
    output: true
    permalink: /policies/:path/
  policies:
    output: true
    permalink: /amendments/:path/
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: ''
      type: 'policies'
    values:
      layout: 'policy'
title: ''
