markdown: kramdown
theme: jekyll-theme-primer
sass:
  sass_dir: assets/css
collections:
  policies:
    output: true
    permalink: /policies/:path/
  amendments:
    output: true
    permalink: /amendments/:path/
defaults:
  - scope:
      path: ''
      type: policies
    values:
      layout: policy
  - scope:
      path: ''
      type: amendments
    values:
      layout: amendment
  - scope:
      path: ''
    values:
      layout: default
title: ''
