on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Prepare web view
    steps:
      - name: Checkout the action
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          ref: master
      - name: Checkout the full repository
        uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: master
          fetch-depth: 0
      - name: Install dependencies
        run: |
          cd ./.github/action
          yarn
      - name: Add PRs and their diffs to the gh-pages version
        id: hello
        uses: ./.github/action
