on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pwd
          ls -la
          yarn
      - name: Hello world action step
        id: hello
        uses: ./.github/action
        with:
          who-to-greet: 'Mona the Octocat'
