on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Add PRs and their diffs to the gh-pages version
    steps:
      - name: Checkout the action
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Checkout the full repository
        uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: master
          fetch-depth: 0
      - name: Install dependencies
        run: |
          cd ./.github/action
          yarn
      - name: Add PRs and their diffs to the gh-pages version
        id: hello
        uses: ./.github/action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit the changes
        run: |
          cd gh-pages
          git add .
          git config --local user.email "charlie_harding@icloud.com"
          git config --local user.name "Charlie Harding"
          message="Update pull requests on gh-pages"
          git commit -m "$message"
          echo git commit-tree -m "$message" -p master -p gh-pages gh-pages
          hash=$(git commit-tree -m "$message" -p master -p gh-pages gh-pages)
          echo git checkout $hash
          git checkout $hash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: gh-pages
          branch: gh-pages
